" All of the plugins are installed with Vundle from this file.
source ~/.vim/vundle.vim

source ~/.vim/config.vim

source ~/.vim/functions.vim

source ~/.vim/mapping.vim

source ~/.vim/happy.vim

source ~/.vim/plugins.vim

source ~/.vim/autocmds.vim

"" Include user's local vim config
if filereadable(expand("~/.vimrc.local"))
    source ~/.vimrc.local
endif
